version: '3'
services:
  php:
    image: php:7.4-rc-fpm-buster
    volumes:
      - ./code/:/var/www/html
    ports:
      - 9000:9000
  nginx:
    image: nginx:1.17.5
    volumes:
      - ./code/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8820:80

  redis:
     image: redis:latest
     ports:
       - 6379:6379
